TaskManagement/py/urls.py
from django.urls import path

from . import views
#AS 20210929 画像対応
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#AE 20210929 画像対応

app_name = 'TaskManagement'
urlpatterns = [
    #Index.html
    path('', views.index, name='index'),
    #AS 20210926
    # ex: /TaskManagement/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    path('specifics/<int:question_id>/', views.detail, name='detail'),
    # ex: /TaskManagement/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /TaskManagement/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # ex: /TaskManagement/5/olfe/
    path('<int:question_id>/olfe/', views.olfe, name='olfe'),
    # ex: /TaskManagement/5/olfe/
    path('<str:question_text>/str_olfe/', views.str_olfe, name='str_olfe'),
    #AE 20210926
    
    #AS 20210928
    path('regist_task/', views.goto_regist_task, name='goto_regist_task'),
    path('registed_task/', views.regist_task, name='regist_task'),
    path('detail_task/<int:task_id>/', views.goto_detail_task, name='detail_task'),
    path('update_task/', views.update_task, name='update_task'),
    path('delete_task/', views.delete_task, name='delete_task'),
    path('taskTable/', views.taskTable, name='taskTable'),
    path('test01/', views.test01, name='test01'),
    #AE 20210928
] + static (settings.STATIC_URL, document_root=settings.STATIC_ROOT)

TaskManagement/urls.py
from django.urls import path

from . import views
#AS 20210929 画像対応
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#AE 20210929 画像対応

app_name = 'TaskManagement'
urlpatterns = [
    #Index.html
    path('', views.index, name='index'),
    #AS 20210926
    # ex: /TaskManagement/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    path('specifics/<int:question_id>/', views.detail, name='detail'),
    # ex: /TaskManagement/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /TaskManagement/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # ex: /TaskManagement/5/olfe/
    path('<int:question_id>/olfe/', views.olfe, name='olfe'),
    # ex: /TaskManagement/5/olfe/
    path('<str:question_text>/str_olfe/', views.str_olfe, name='str_olfe'),
    #AE 20210926
    #AS 20210928
    path('regist_task/', views.goto_regist_task, name='goto_regist_task'),
    path('registed_task/', views.regist_task, name='regist_task'),
    path('detail_task/<int:task_id>/', views.goto_detail_task, name='detail_task'),
    path('update_task/', views.update_task, name='update_task'),
    path('delete_task/', views.delete_task, name='delete_task'),
    #AE 20210928
] 

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    #Index.html
    path('', views.index, name='index'),
    #AS 20210926
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    path('specifics/<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # ex: /polls/5/olfe/
    path('<int:question_id>/olfe/', views.olfe, name='olfe'),
    # ex: /polls/5/olfe/
    path('<str:question_text>/str_olfe/', views.str_olfe, name='str_olfe'),
    #AE 20210926
]

TaskManagement/py/models.py
"""
参考サイト
■Django モデルフィールド：データベースフィールド 型対応表
https://qiita.com/okoppe8/items/13ad7b7d52fd6a3fd3fc

"""
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    # Questionに対してリレーションを貼る
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text


class Task(models.Model):
    # TASKに対してリレーションを貼る
    task_title = models.CharField(max_length=256)
    task_detail = models.TextField(max_length=10000)
    task_tant = models.CharField(max_length=64)
    task_log = models.TextField(max_length=10000)
    task_kihyb = models.DateTimeField('date published')
    task_kign =  models.DateTimeField('date published')
    task_status = models.CharField(max_length=32)
    delflg = models.CharField(max_length=1)
    def __str__(self):
        return self.task_title

TaskManagement/py/views.py
import datetime

from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.contrib import messages

from .models import (
    Choice,
    Question,
    Task
)
from .process import (
    A010_Index,
    A020_GoToRegistTask,
    A030_RegistTask,
    A040_GoToDetailTask,
    A050_UpdateTask,
    A060_DeleteTask,
    A070_IchiranTable
)
from .process import C010_Const

#DS 2021/10/03 クラス構成対応
#共通処理
#一覧用のコンテキストを作成する
#def make_context_index():
#    latest_question_list = Question.objects.order_by('-pub_date')[:5]
#    #AS 20210927
#    all_task_list = Task.objects.filter(delflg="0").order_by('id')
#    #AE 20210927
#    context = {'latest_question_list': latest_question_list,
#                'all_task_list': all_task_list,
#                }
#    return context
#DE 2021/10/03 クラス構成対応

#共通メソッド-----------------------------------------------------------------------------------------------------
def setMessages(request,list_msg):
    """
    C:\Python39\Lib\site-packages\django\contrib\messages
    messages.constants.ERROR...
    ⇒C010_Const.pyにて再定義したため、こちらを利用
        DEBUG = 10
        INFO = 20
        SUCCESS = 25
        WARNING = 30
        ERROR = 40
    使用例）
    (1)下記のように、"level"と"msg"で1つのjsonを作成する。この際、「C010_Const」からエラーレベルを選択する。
        json_msg={"level":C010_Const.ERROR,"msg":"タイトルが未入力です"}
    (2)下記のように、list_msgに作成したメッセージ情報を追加する、
        list_msg.append(json_msg)
    """
    for json_msg in list_msg:
        #messages.error(request, massage)
        messages.add_message(request,json_msg["level"], json_msg["msg"])
#-----------------------------------------------------------------------------------------------------------------


#目次
def index(request):
    #CS 2021/10/03 クラス構成対応
    #context = make_context_index()
    #print(type(request))
    #print(request)
    #print(type(request.POST))
    #print(request.POST)
    #print(type(request.GET))
    #print(request.GET)
    list_msg = []
    json_main = A010_Index.main(request,list_msg)
    context = json_main["context"]
    template = json_main["template"]
    #CE 2021/10/03 クラス構成対応
    setMessages(request,list_msg)
    return render(request, template, context)

#タスク登録画面に遷移
def goto_regist_task(request):
    list_msg = []
    json_main = A020_GoToRegistTask.main(request,list_msg)
    context = json_main["context"]
    template = json_main["template"]
    setMessages(request,list_msg)
    return render(request, template, context)

#タスク詳細画面に遷移
def goto_detail_task(request,task_id):
    list_msg = []
    json_main = A040_GoToDetailTask.main(request,list_msg,task_id)
    context = json_main["context"]
    template = json_main["template"]
    setMessages(request,list_msg)
    return render(request, template, context)

#タスク更新
def update_task(request):
    list_msg = []
    json_main = A050_UpdateTask.main(request,list_msg)
    context = json_main["context"]
    template = json_main["template"]
    setMessages(request,list_msg)
    return render(request, template, context)

#タスク登録
def regist_task(request):
    #メッセージリストを宣言
    list_msg = []
    #アクションクラスを呼び出し
    json_main = A030_RegistTask.main(request,list_msg)
    #引数用のコンテキスト、遷移先を取得
    context = json_main["context"]
    template = json_main["template"]
    #メッセージをセット
    setMessages(request,list_msg)
    #返却
    return render(request, template, context)
    """
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'TaskManagement/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return render(request, 'TaskManagement/regist_task.html')
    """

def taskTable(request):
    #try:
    #ビュープロセスクラスを呼び出し
    json_view = A070_IchiranTable.main(request)
    #「render」か「redirect」かを判断
    flg_return = json_view["flg_return"]
    if flg_return == "0":
        #「render」の場合
        context = json_view["context"]
        template = json_view["template"]
        return render(request, template, context)
    elif flg_return == "1":
        #「redirect」の場合
        path_name = json_view["path_name"]
        return redirect(path_name)
    """
    except Exception as e :
        #システムエラー共通処理
        C030_MessageUtil.systemErrorCommonMethod()
        #システムエラー画面に遷移
        return redirect(ERR_PATH_NAME)
    """


    #タスク削除（論理削除）
def delete_task(request):
    #メッセージリストを宣言
    list_msg = []
    #アクションクラスを呼び出し
    json_main = A060_DeleteTask.main(request,list_msg)
    #引数用のコンテキスト、遷移先を取得
    context = json_main["context"]
    template = json_main["template"]
    #メッセージをセット
    setMessages(request,list_msg)
    #返却
    return render(request, template, context)


    #テスト01
def test01(request):
    #list_newsInfo = S006_GetKeibaNews.main(0)
    #メッセージリストを宣言
    template = "TaskManagement/test01.html"
    #context = {"list_newsInfo":list_newsInfo}
    context = {}
    #返却
    return render(request, template, context) 

#===============================================================================================================
#オルフェーブル
def olfe(request, question_id):
    return HttpResponse("You're オルフェーブル No %s." % question_id)

#文字フェーブル
def str_olfe(request, question_text):
    return HttpResponse("You're %sフェーブル" % question_text)

#詳細
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'TaskManagement/detail.html', {'question': question})

#結果
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'TaskManagement/results.html', {'question': question})

#投票
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'TaskManagement/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('TaskManagement:results', args=(question.id,)))

TaskManagement/templates/TaskManagement/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'TaskManagement:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

TaskManagement/templates/TaskManagement/detail_task copy.html
{% extends "TaskManagement/base.html" %}
<!-- <html-->
    <!-- <header> -->
        {% block head %}
        {% load static %}
        <link rel="stylesheet" href="{% static '/css/taskmanagement.css' %}">
        <script>
            function action_ichiran(){
                document.getElementById('form').action = "{% url 'TaskManagement:index' %}";
                document.getElementById('form').submit();
            }
            function action_delete(){
                if( confirm("削除します。よろしいですか？") ) {
                    document.getElementById('form').action = "{% url 'TaskManagement:delete_task'%}";
                    document.getElementById('form').submit();
                }
            }
            function action_update(){
                document.getElementById('form').action = "{% url 'TaskManagement:update_task'%}";
                document.getElementById('form').submit();
            }

        </script>
        <!-- ↓body閉じタグ直前でjQueryを読み込む -->
        <!-- <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script> -->
        <!-- <script type="text/javascript" src="{% static '/js/min.js' %}"></script> -->
        {% endblock head %}
    <!-- </header> -->
    <!-- <body> -->
        {% block header %}
            <h1>課題詳細</h1>
        {% endblock header %}

        {% block content %}
        <button id="openModal">Open modal</button>

        <!-- モーダルエリアここから -->
        {% if messages %}
        <section id="modalArea" class="modalArea">
        <div id="modalBg" class="modalBg"></div>
        <div class="modalWrapper">
            <div class="modalContents">
            <h1>モーダル画面</h1>
            <p>[キャンセル]　[OK]</p>
            </div>
            <ul class="messages">
                {% for message in messages %}
                    {{ message }}
                {% endfor %}
            </ul>
            <div id="closeModal" class="closeModal">
            ×
            </div>
        </div>
        </section>
        {% endif %}
        <!-- モーダルエリアここまで -->
        <br>
        <!-- メッセージエリアここから -->
        {% if messages %}
            <div  class="message">
                {% for message in messages %}
                    <br>{{ message }}
                {% endfor %}
            </div>
        {% endif %} 
        <!-- メッセージエリアここまで -->
        <table border="0"  cellspacing="5" cellpadding="5" bordercolor="#333333">
            <tr>
                <td align="left" valign="top">

        <!--入力エリア==============================================================================================================-->

                    <form id='form' name='form' method="post">
                        {% csrf_token %}
                        {% for task in list_one_task %}
                        <table border="0"  cellspacing="5" cellpadding="5" bordercolor="#333333">
                            <tr>
                                <td align="left">
                                    <input type="image" 
                                        src="{% static '/images/back_ichiran_01.png' %}"
                                        onmouseover='src="{% static '/images/back_ichiran_02.png' %}"'  
                                        onmouseout='src="{% static '/images/back_ichiran_01.png' %}"'  
                                        value="一覧に戻る" 
                                        onclick="action_ichiran();" 
                                        width="140" height="35"
                                    >
                                </td>
                                <td align="right"> 
                                    <input type="image" 
                                        src="{% static '/images/del_task_01.png' %}"
                                        onmouseover='src="{% static '/images/del_task_02.png' %}"'
                                        onmouseout='src="{% static '/images/del_task_01.png' %}"'  
                                        value="課題を削除" 
                                        onclick="action_delete();" 
                                        width="140" height="35"
                                    >
                                    <input type="image" 
                                        src="{% static '/images/update_task_01.png' %}"
                                        onmouseover='src="{% static '/images/update_task_02.png' %}"'
                                        onmouseout='src="{% static '/images/update_task_01.png' %}"'  
                                        value="課題を更新" 
                                        onclick="action_update();" 
                                        width="140" height="35"
                                    >
                                </td>
                            </tr>
                            <tr>
                                <td>課題No：{{ task.id }}
                                    <input type="hidden" id="task_id" name="task_id"  value="{{task.id}}" >
                                </td>
                            </tr>
                            <tr>
                                <td colspan= "2">
                                    課題名：<br>
                                    <input type="text" id="task_title" name="task_title" required minlength="0" maxlength="256" size="100%" value= "{{task.task_title}}" >
                                </td>
                            </tr>
                            <tr>
                                <td>
                                    担当：<input type="text" id="task_tant" name="task_tant" required minlength="0" maxlength="64" size="30%" value="{{task.task_tant}}" >
                                </td>
                                <td align="right">
                                    期限：
                                    <input type="date" id="task_kign" name="task_kign" value="{{ hyoji_kigen }}">
                                    ステータス：
                                    <input type="text" id="task_status" name="task_status" required minlength="0" maxlength="64" size="20"  value="{{ task.task_status }}">
                                </td>
                            </tr>
                            <tr>
                                <td colspan= "2">
                                    課題詳細：<br>
                                    <textarea id="task_detail" name="task_detail" cols="128" rows="10" wrap="hard">{{ task.task_detail }}</textarea>
                                </td>
                            </tr>
                            <tr>
                                <td colspan= "2">
                                    対応内容：<br>
                                    <textarea id="task_log" name="task_log" cols="128" rows="67" wrap="hard">{{ task.task_log }}</textarea>
                                </td>
                            </tr>
                        </table>
                        {% endfor %}
                    </form>
                </td>
        <!--広告エリア==============================================================================================================-->
        <script>
            function goto_ad_01(){
                window.open('https://db.netkeiba.com/horse/2002100816/', '_blank'); 
            }
            function goto_ad_02(){
                window.open('https://db.netkeiba.com/horse/2004104258/', '_blank'); 
            }
            function goto_ad_03(){
                window.open('https://db.netkeiba.com/horse/1985104409/', '_blank'); 
            }
            function goto_ad_04(){
                window.open('https://db.netkeiba.com/horse/1993109219/', '_blank'); 
            }
            function goto_ad_05(){
                window.open('https://db.netkeiba.com/horse/1983109008/', '_blank'); 
            }
            function goto_ad_06(){
                window.open('https://db.netkeiba.com/horse/1981107017/', '_blank'); 
            }
            function goto_ad_07(){
                window.open('https://db.netkeiba.com/horse/1996100292/', '_blank'); 
            }
            function goto_netkeiba_orfevre(){
                window.open('https://db.netkeiba.com/horse/2008102636/', '_blank'); 
            }
        </script>
                <td align="right" valign="top">
                    <input type="image" 
                        src="{% static '/images/advertisement/deep_01.jpg' %}"
                        onmouseover='src="{% static '/images/advertisement/deep_02.jpg' %}"'  
                        onmouseout='src="{% static '/images/advertisement/deep_03.jpg' %}"'  
                        value="ディープインパクト" 
                        onclick="goto_ad_01();" 
                        width="320" height="180"
                    >
                    <br>
                    <input type="image" 
                        src="{% static '/images/advertisement/vodka_01.jpg' %}"
                        onmouseover='src="{% static '/images/advertisement/vodka_02.jpg' %}"'  
                        onmouseout='src="{% static '/images/advertisement/vodka_03.jpg' %}"'  
                        value="ウォッカ" 
                        onclick="goto_ad_02();" 
                        width="320" height="180"
                    >
                    <br>
                    <input type="image" 
                        src="{% static '/images/advertisement/supercreek_01.jpg' %}"
                        onmouseover='src="{% static '/images/advertisement/supercreek_02.jpg' %}"'  
                        onmouseout='src="{% static '/images/advertisement/supercreek_03.jpg' %}"'  
                        value="スーパークリーク" 
                        onclick="goto_ad_03();" 
                        width="320" height="180"
                    >
                    <br>
                    <input type="image" 
                        src="{% static '/images/advertisement/bubble_01.jpg' %}"
                        onmouseover='src="{% static '/images/advertisement/bubble_02.jpg' %}"'  
                        onmouseout='src="{% static '/images/advertisement/bubble_03.jpg' %}"'   
                        value="バブルガムフェロー" 
                        onclick="goto_ad_04();" 
                        width="320" height="180"
                    >
                    <br>
                    <input type="image" 
                        src="{% static '/images/advertisement/horlicks_01.jpg' %}"
                        onmouseover='src="{% static '/images/advertisement/horlicks_02.jpg' %}"'  
                        onmouseout='src="{% static '/images/advertisement/horlicks_03.jpg' %}"'
                        value="ホーリックス" 
                        onclick="goto_ad_05();" 
                        width="320" height="180"
                    >
                    <br>
                    <input type="image" 
                        src="{% static '/images/advertisement/rudolf_01.jpg' %}"
                        onmouseover='src="{% static '/images/advertisement/rudolf_02.jpg' %}"'  
                        onmouseout='src="{% static '/images/advertisement/rudolf_03.jpg' %}"'  
                        value="シンボリルドルフ" 
                        onclick="goto_ad_06();" 
                        width="320" height="180"
                    >
                    <br>
                    <input type="image" 
                        src="{% static '/images/advertisement/tmopera_01.jpg' %}"
                        onmouseover='src="{% static '/images/advertisement/tmopera_02.jpg' %}"'  
                        onmouseout='src="{% static '/images/advertisement/tmopera_03.jpg' %}"'  
                        value="テイエムオペラオー" 
                        onclick="goto_ad_07();" 
                        width="320" height="180"
                    >
                    <br>
                    <input type="image" 
                        src="{% static '/images/advertisement/orfavre_01.png' %}"
                        onmouseover='src="{% static '/images/advertisement/orfavre_01.png' %}"'  
                        onmouseout='src="{% static '/images/advertisement/orfavre_01.png' %}"'  
                        value="オルフェーブル" 
                        onclick="goto_netkeiba_orfevre();" 
                        width="50" height="2"
                    >
                </td>
            </tr>
        </table>
        {% endblock content %}
    <!-- </body>>-->
<!-- </html>-->

TaskManagement/templates/TaskManagement/err500.html
<html>
    <header>
        {% load static %}
        <link rel="stylesheet" href="{% static '/css/taskmanagement.css' %}">
    </header>
    <body>
        <h1>システムエラー</h1>
    </body>
</html>

TaskManagement/templates/TaskManagement/index copy.html
{% extends "TaskManagement/base.html" %}
{% block head %}
    {% load static %}
    <link rel="stylesheet" href="{% static '/css/taskmanagement.css' %}">
    <script>
        function action_add_task(){
            location.href = "{% url 'TaskManagement:goto_regist_task'%}";
        }
    </script>
{% endblock head %}
{% block header %}
    <h1 >課題一覧</h1>
{% endblock header %}
{% block content %}

    <!--　旧コード
    {% if latest_question_list %}
        <ul>
        {% for question in latest_question_list %}
            <li><a href="{% url 'TaskManagement:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p></p>
    {% endif %}
    -->
    <br>
    <!-- メッセージエリアここから -->
    {% if messages %}
        <div  class="message">
            {% for message in messages %}
                <br>{{ message }}
            {% endfor %}
        </div>
    {% endif %}
    <!-- メッセージエリアここまで -->
    <table>
        <tr>
            <td align="right" > 
                <input type="image" id = "add_task"
                src="{% static '/images/add_task_01.png' %}"
                onmouseover='src="{% static '/images/add_task_02.png' %}"'  
                onmouseout='src="{% static '/images/add_task_01.png' %}"'  
                value="タスクを追加" 
                onclick="action_add_task();" 
                width="140" height="35"
            >
            </td>
        </tr>
        <tr>
            <td align="right" > 
                <table class="table_layout" cellpadding="1" >
                    {% if all_task_list %}
                        <thead>
                            <tr class="table_hedder">
                                <th class="th_layout" scope="col">No</th>
                                <th class="th_layout" scope="col">起票日</th>
                                <th class="th_layout" scope="col">期限</th>
                                <th class="th_layout" scope="col">タイトル</th>
                                <th class="th_layout" scope="col">担当者</th>
                            <!--<th class="th_layout" scope="col">詳細</th>-->
                            <!--<th class="th_layout" scope="col">対応内容</th>-->
                                <th scope="col">ステータス</th>
                            </tr>
                        </thead>
                        <ul>
                        {% for task in all_task_list %}
                            <tr align="left" valign="top" class="tr_layout">
                                <td class="td_layout" width="40">{{ task.id }}</td>
                                <td class="td_layout" width="80">{{ task.task_kihyb | date:"y/m/d" }}</td>
                                <td class="td_layout" width="80">{{ task.task_kign | date:"y/m/d" }}</td>
                                <td class="td_layout" width="300"><a href="{% url 'TaskManagement:detail_task' task.id %}">{{ task.task_title }}</a></td>
                                <td class="td_layout" width="80">{{ task.task_tant }}</td>
                            <!--<td class="td_layout" width="500">{{ task.task_detail }}</td>-->
                            <!--<td class="td_layout" width="700">{{ task.task_log }}</td>-->
                                <td class="td_layout" width="100" align="center" valign="middle">{{ task.task_status }}</td>
                            </tr>
                        {% endfor %}
                        </ul>
                    {% else %}
                        <p>タスクはありません</p>
                    {% endif %}
                </table>
            </td>
        </tr>
        <tr>
            <td align="right" > 
                <input type="image" id = "add_task"
                src="{% static '/images/add_task_01.png' %}"
                onmouseover='src="{% static '/images/add_task_02.png' %}"'  
                onmouseout='src="{% static '/images/add_task_01.png' %}"'  
                value="タスクを追加" 
                onclick="action_add_task();" 
                width="140" height="35"
            >
            </td>
        </tr>
    </table>        
{% endblock content %}

TaskManagement/templates/TaskManagement/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'TaskManagement:detail' question.id %}">Vote again?</a>

TaskManagement/templates/TaskManagement/taskTable.html
{% extends "TaskManagement/base.html" %}
{% block head %}
{% load static %}
<link rel="stylesheet" href="{% static '/css/taskmanagement.css' %}">
<script>
    function action_add_task() {
        location.href = "{% url 'TaskManagement:goto_regist_task'%}";
    }
    function action_goto_detail_task() {
    }
</script>
{% endblock head %}
{% block header %}
<h1>課題表</h1>
{% endblock header %}
{% block content %}

<br>
<!-- メッセージエリアここから -->
<div class="container">
    {% if messages %}
    <div class="row">
        {% for message in messages %}
    </div>
    <div class="col-sm-12">
        <br>
        <div class="alert alert-info" role="alert">{{ message }}</div>
    </div>
</div>
{% endfor %}
</div>
{% endif %}
</div>
<!-- メッセージエリアここまで -->
<!-- テーブルエリア -->
<div class="container">
    <div class="table-responsive">
        {% if all_task_list %}
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>No</th>
                    <th>起票日</th>
                    <th>期限日</th>
                    <th>課題タイトル</th>
                    <th>担当</th>
                    <th>状態</th>
                </tr>
            </thead>
            <tbody>
                {% for task in all_task_list %}
                <tr>
                    <th scope="row">{{ task.id }}</th>
                    <td>{{ task.task_kihyb | date:"y/m/d" }}</td>
                    <td>{{ task.task_kign | date:"y/m/d" }}</td>
                    <td><a href="{% url 'TaskManagement:detail_task' task.id %}">{{ task.task_title }}</a></td>
                    <td>{{ task.task_tant }}</td>
                    <td>{{ task.task_status }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>
</div>
<!-- テーブルエリア -->

<br>
<br>
{% endblock content %}