TaskManagement/urls.py
from django.urls import path

from . import views
#AS 20210929 画像対応
from django.conf import settings
from django.contrib.staticfiles.urls import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
#AE 20210929 画像対応

app_name = 'TaskManagement'
urlpatterns = [
    #Index.html
    path('', views.index, name='index'),
    #AS 20210926
    # ex: /TaskManagement/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    path('specifics/<int:question_id>/', views.detail, name='detail'),
    # ex: /TaskManagement/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /TaskManagement/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # ex: /TaskManagement/5/olfe/
    path('<int:question_id>/olfe/', views.olfe, name='olfe'),
    # ex: /TaskManagement/5/olfe/
    path('<str:question_text>/str_olfe/', views.str_olfe, name='str_olfe'),
    #AE 20210926
    #AS 20210928
    path('regist_task/', views.goto_regist_task, name='goto_regist_task'),
    path('registed_task/', views.regist_task, name='regist_task'),
    path('detail_task/<int:task_id>/', views.goto_detail_task, name='detail_task'),
    path('update_task/', views.update_task, name='update_task'),
    path('delete_task/', views.delete_task, name='delete_task'),
    #AE 20210928
] 

polls/urls.py
from django.urls import path

from . import views

app_name = 'polls'
urlpatterns = [
    #Index.html
    path('', views.index, name='index'),
    #AS 20210926
    # ex: /polls/5/
    #path('<int:question_id>/', views.detail, name='detail'),
    path('specifics/<int:question_id>/', views.detail, name='detail'),
    # ex: /polls/5/results/
    path('<int:question_id>/results/', views.results, name='results'),
    # ex: /polls/5/vote/
    path('<int:question_id>/vote/', views.vote, name='vote'),
    # ex: /polls/5/olfe/
    path('<int:question_id>/olfe/', views.olfe, name='olfe'),
    # ex: /polls/5/olfe/
    path('<str:question_text>/str_olfe/', views.str_olfe, name='str_olfe'),
    #AE 20210926
]

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)


class Choice(models.Model):
    # Questionに対してリレーションを貼る
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

polls/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse

from .models import Choice, Question

#目次
"""
def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")
"""
"""
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list': latest_question_list,
    }
    return HttpResponse(template.render(context, request))
"""
def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

#詳細
"""
def detail(request, question_id):
    return HttpResponse("You're looking at question %s." % question_id)
"""
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

#結果
"""
def results(request, question_id):
    response = "You're looking at the results of question %s."
    return HttpResponse(response % question_id)
"""
def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

#投票
"""
def vote(request, question_id):
    return HttpResponse("You're voting on question %s." % question_id)
"""
def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

#オルフェ
def olfe(request, question_id):
    return HttpResponse("You're オルフェーブル No %s." % question_id)

#文字オルフェ
def str_olfe(request, question_text):
    return HttpResponse("You're %sフェーブル" % question_text)
    

polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'TaskManagement:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
{% endfor %}
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if latest_question_list %}
    <h1>ページのタイトル</h1>
    <ul>
    {% for question in latest_question_list %}
        <!--<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>-->
        <!--<li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>-->
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
        {% endfor %}
    </ul>
    <ul>
        {% for question in latest_question_list %}
            <!--<li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>-->
            <li><a href="{% url 'polls:str_olfe' question.question_text %}">{{ question.question_text }}</a></li>
            {% endfor %}
        </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'TaskManagement:detail' question.id %}">Vote again?</a>